version: '3.8'

# Configuration réseau
networks:
  mcp-network:
    driver: bridge
    name: mcp-crawl4ai-network

# Variables d'environnement communes
x-env: &default-env
  # Configuration du serveur
  TRANSPORT: sse
  HOST: 0.0.0.0
  PORT: 8051
  
  # Clés API (requises)
  OPENAI_API_KEY: ${OPENAI_API_KEY:?"OPENAI_API_KEY doit être défini"}
  SUPABASE_URL: ${SUPABASE_URL:?"SUPABASE_URL doit être défini"}
  SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY:?"SUPABASE_SERVICE_KEY doit être défini"}
  
  # Configuration du modèle (optimisé pour CPU)
  MODEL_CHOICE: ${MODEL_CHOICE:-gpt-4}
  
  # Désactiver les fonctionnalités gourmandes en GPU
  USE_CONTEXTUAL_EMBEDDINGS: false
  USE_HYBRID_SEARCH: false
  USE_AGENTIC_RAG: false
  USE_RERANKING: false
  USE_KNOWLEDGE_GRAPH: false
  
  # Optimisations Python
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONFAULTHANDLER: 1
  PYTHONPATH: /app
  
  # Configuration des chemins
  CRAWL4_AI_BASE_DIRECTORY: /app/data
  PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
  
  # Chemins de l'application
  APP_DATA_DIR: /app/data
  LOG_DIR: /app/logs
  
  # Configuration des répertoires de cache
  CACHE_DIR: /app/.cache
  PIP_CACHE_DIR: /app/.cache/pip
  XDG_CACHE_HOME: /app/.cache
  
  # Configuration pour éviter les téléchargements inutiles
  TRANSFORMERS_OFFLINE: 1
  HF_DATASETS_OFFLINE: 1
  HF_EVALUATE_OFFLINE: 1
  HUGGINGFACE_HUB_CACHE: /app/.cache/huggingface/hub
  TORCH_HOME: /app/.cache/torch
  
  # Configuration du logging
  LOG_LEVEL: INFO
  
  # Configuration du service
  API_HOST: ${API_HOST:-0.0.0.0}
  API_PORT: ${API_PORT:-8051}

services:
  # Service principal MCP Crawl4AI RAG
  mcp-crawl4ai-rag:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8051
    
    ports:
      - "${API_PORT:-8051}:8051"
    
    environment:
      <<: *default-env
    
    # Volumes pour la persistance et le cache
    volumes:
      - mcp-crawl4ai-data:/app/data
      - mcp-crawl4ai-logs:/app/logs
      - mcp-cache:/root/.cache
    
    # Configuration des ressources (optimisées pour CPU)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    
    # Configuration de la santé
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8051/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    
    # Redémarrage automatique sauf arrêt manuel
    restart: unless-stopped
    
    # Configuration réseau
    networks:
      - mcp-network
    
    # Commande de démarrage personnalisée
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8051", "--proxy-headers"]

# Définition des volumes persistants
volumes:
  # Volume pour les données persistantes
  mcp-crawl4ai-data:
    name: mcp-crawl4ai-data
    driver: local
  # Volume pour les logs
  mcp-crawl4ai-logs:
    name: mcp-crawl4ai-logs
    driver: local
  # Volume pour le cache
  mcp-cache:
    name: mcp-crawl4ai-cache
    driver: local
