version: '3.8'

services:
  mcp-crawl4ai:
    build:
      context: .
      args:
        PORT: 8051
    ports:
      - "8051:8051"
    environment:
      - TRANSPORT=sse
      - HOST=0.0.0.0
      - PORT=8051
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}
      - MODEL_CHOICE=${MODEL_CHOICE:-gpt-4}
      - USE_CONTEXTUAL_EMBEDDINGS=${USE_CONTEXTUAL_EMBEDDINGS:-false}
      - USE_HYBRID_SEARCH=${USE_HYBRID_SEARCH:-false}
      - USE_AGENTIC_RAG=${USE_AGENTIC_RAG:-false}
      - USE_RERANKING=${USE_RERANKING:-false}
      - OLAMA_BASE_URL=${OLAMA_BASE_URL:-http://host.docker.internal:11434}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-nomic-embed-text}
    restart: unless-stopped

volumes:
  postgres_data:
