version: '3.8'

# Variables d'environnement communes
x-env: &default-env
  # Configuration du serveur
  TRANSPORT: sse
  HOST: 0.0.0.0
  PORT: 8002
  
  # Clés API (requises)
  OPENAI_API_KEY: ${OPENAI_API_KEY:?"OPENAI_API_KEY doit être défini"}
  SUPABASE_URL: ${SUPABASE_URL:?"SUPABASE_URL doit être défini"}
  SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY:?"SUPABASE_SERVICE_KEY doit être défini"}
  
  # Configuration du modèle
  MODEL_CHOICE: ${MODEL_CHOICE:-gpt-4}
  
  # Fonctionnalités optionnelles
  USE_CONTEXTUAL_EMBEDDINGS: ${USE_CONTEXTUAL_EMBEDDINGS:-false}
  USE_HYBRID_SEARCH: ${USE_HYBRID_SEARCH:-false}
  USE_AGENTIC_RAG: ${USE_AGENTIC_RAG:-false}
  USE_RERANKING: ${USE_RERANKING:-false}
  USE_KNOWLEDGE_GRAPH: ${USE_KNOWLEDGE_GRAPH:-false}
  
  # Configuration Neo4j (si USE_KNOWLEDGE_GRAPH=true)
  NEO4J_URI: ${NEO4J_URI:-bolt://neo4j:7687}
  NEO4J_USER: ${NEO4J_USER:-neo4j}
  NEO4J_PASSWORD: ${NEO4J_PASSWORD:?"NEO4J_PASSWORD doit être défini si USE_KNOWLEDGE_GRAPH=true"}
  
  # Optimisations
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONFAULTHANDLER: 1
  CRAWL4_AI_BASE_DIRECTORY: /app/data

services:
  mcp-crawl4ai-rag:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8002:8002"
    
    environment:
      <<: *default-env
      
      # Configuration des répertoires de cache
      CACHE_DIR: /app/.cache
      HUGGINGFACE_HUB_CACHE: /app/.cache/huggingface/hub
      TORCH_HOME: /app/.cache/torch
    
    # Volumes pour la persistance des données
    volumes:
      - model_cache:/app/.cache
      - ./logs:/app/logs
    
    # Configuration du déploiement
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    # Redémarrage automatique
    restart: unless-stopped
    
    # Configuration de la santé
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8051/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# Définition des volumes
volumes:
  model_cache:
    driver: local
  postgres_data:
    driver: local
