[tool.poetry]
name = "crawl4ai-mcp"
version = "0.1.0"
description = "MCP server for integrating web crawling and RAG into AI agents and AI coding assistants"
authors = ["Windsurf Cascade <support@windsurf.ai>"]
readme = "README.md"
license = "MIT"
packages = [{include = "src"}]
package-mode = true

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.115.14"
uvicorn = {extras = ["standard"], version = "0.27.1"}
pydantic = "^2.7.0"
pydantic-settings = "2.7.0"
python-dotenv = "^1.1.0"
httpx = "^0.28.1"
anyio = "4.5.0"

# MCP et intégrations
mcp = "^1.9.4"
fastmcp = "2.9.2"

# Web et requêtes
requests = "2.31.0"
beautifulsoup4 = "4.12.3"
lxml = "^5.3.0"

# Base de données et ORM
sqlalchemy = "2.0.27"
alembic = "1.13.1"
pandas = "2.2.1"

# Authentification et sécurité
python-jose = {extras = ["cryptography"], version = "3.3.0"}
passlib = {extras = ["bcrypt"], version = "1.7.4"}

# Traitement de texte et données
python-slugify = "8.0.1"
pyyaml = "6.0.1"
jinja2 = "3.1.3"

# RAG et IA
crawl4ai = {extras = ["cpu"], version = "0.6.2"}
sentence-transformers = "3.0.0"
openai = "1.71.0"


# Autres dépendances
fastapi-pagination = "0.12.11"
python-multipart = "0.0.9"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
black = "^23.12.1"
isort = "^5.13.2"
mypy = "^1.8.0"
types-requests = "^2.31.0.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
