[tool.poetry]
name = "mcp-crawl4ai-rag"
version = "0.1.0"
description = "MCP Crawl4AI RAG Service (CPU only)"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
pydantic = "^2.0.0"
fastmcp = "^2.9.2"
crawl4ai = "^0.6.0"
transformers = "^4.30.0"
sentence-transformers = "^2.2.0"
torch = {version = "2.2.2", source = "pytorch"}
torchvision = {version = "0.17.2", source = "pytorch"}
torchaudio = {version = "2.2.2", source = "pytorch"}
faiss-cpu = "^1.7.0"
numpy = "^1.26.0"
httpx = {extras = ["http2"], version = "^0.28.1"}
supabase = "^2.0.0"
loguru = "^0.7.0"
neo4j = "^5.12.0"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
openai = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "supplemental"
