[tool.poetry]
name = "mcp-crawl4ai-rag"
version = "0.1.0"
description = "MCP Crawl4AI RAG Service"
authors = ["Windsurf Cascade <support@windsurf.ai>"]
readme = "README.md"
packages = [{include = "src"}]
package-mode = true

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.28.0"}
python-dotenv = "^1.0.0"
fastmcp = "^2.9.0"
pydantic = "^2.7.0"
pydantic-settings = "^2.7.0"
python-multipart = "^0.0.9"
torch = {version = "^2.2.1", source = "pytorch-cpu"}
sentence-transformers = "^2.7.0"
faiss-cpu = "^1.7.4"
httpx = "^0.27.0"
numpy = "^1.26.0"
tqdm = "^4.66.0"
scikit-learn = "^1.4.0"
scipy = "^1.12.0"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "supplemental"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
