[tool.poetry]
name = "crawl4ai-mcp"
version = "0.1.0"
description = "MCP server for integrating web crawling and RAG into AI agents and AI coding assistants"
authors = ["Windsurf Cascade <support@windsurf.ai>"]
readme = "README.md"
license = "MIT"
packages = [{include = "src"}]
package-mode = true

[tool.poetry.dependencies]
python = "^3.12"

# Framework et serveur web
fastapi = {extras = ["all"], version = "^0.115.14"}
uvicorn = {extras = ["standard"], version = "^0.27.0"}
pydantic = {extras = ["email"], version = "^2.7.0"}
pydantic-settings = "^2.7.0"
python-dotenv = "^1.1.0"
httpx = {extras = ["http2"], version = "^0.27.0"}
anyio = "^4.5.0"
gunicorn = "^21.2.0"

# MCP et intégrations
mcp = "^1.9.4"
fastmcp = "2.9.2"
supabase = "^2.5.0"

# Web et requêtes HTTP
requests = "2.31.0"
beautifulsoup4 = "4.12.3"
lxml = "5.3.0"
aiofiles = "^24.1.0"
aiohttp = "^3.11.11"
aiosqlite = "^0.20.0,<1.0.0"
brotli = "^1.1.0"
chardet = "^5.2.0"
click = "^8.1.7"
colorama = "^0.4.0,<1.0.0"
cssselect = "^1.2.0"
fake-useragent = "^2.2.0"
humanize = "^4.10.0"
litellm = "^1.53.1"
nltk = "^3.9.1"
numpy = "^1.26.0,<3.0.0"
pillow = "^10.4.0,<11.0.0"
playwright = "^1.49.0"
psutil = "^6.1.1"
pyopenssl = "^24.3.0"
pyperclip = "^1.8.2"
rank-bm25 = "^0.2.0,<1.0.0"
rich = "^13.9.4"
snowballstemmer = "^2.2.0,<3.0.0"
tf-playwright-stealth = "^1.1.0"
xxhash = "^3.4.0,<4.0.0"

# Base de données et ORM
sqlalchemy = "2.0.27"
alembic = "1.13.1"
pandas = "2.2.1"
neo4j = "^5.14.1"

# Authentification et sécurité
python-jose = {extras = ["cryptography"], version = "3.3.0"}
passlib = {extras = ["bcrypt"], version = "1.7.4"}

# Traitement de texte et données
python-slugify = "8.0.1"
pyyaml = "6.0.1"
jinja2 = ">=3.1.5"

# RAG et IA
crawl4ai = {extras = ["cpu"], version = "0.6.2"}
sentence-transformers = {version = "3.0.0", optional = true}
openai = {version = "1.71.0", optional = true}
huggingface-hub = {version = "^0.23.0", optional = true}
torch = {version = "^2.2.0", optional = true, markers = "sys_platform != 'win32'"}
transformers = {version = "^4.40.0", optional = true}

# Autres dépendances
fastapi-pagination = "0.12.11"
python-multipart = ">=0.0.18"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Configuration Poetry
[tool.poetry.scripts]
start = "src.main:main"

# Groupes de dépendances optionnelles
[tool.poetry.extras]
ai = [
    "sentence-transformers",
    "openai",
    "huggingface-hub",
    "torch",
    "transformers"
]

# Configuration de Black
[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
black = "^23.12.1"
isort = "^5.13.2"
mypy = "^1.8.0"
types-requests = "^2.31.0.10"
